## NumPy

In [34]:
import numpy as np

np.__version__

'1.24.1'

##### Create a Null Vector of Siz 10

In [35]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

##### Size of numpy array

In [36]:
z= np.zeros((10,10))
print(z.size)
z.itemsize

100


8

##### Updating 5th Value of numpy array


In [37]:
z[4][5]=1
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

##### Arange

In [38]:
z= np.arange(4,12)
print(z)
print(z.shape)

[ 4  5  6  7  8  9 10 11]
(8,)


Arrange with intervals

In [45]:
z=np.arange(10,100,5)
z.shape

(18,)

Reshape

In [54]:
x=z.reshape(3,6)
print(x)
x.shape


[[10 15 20 25 30 35]
 [40 45 50 55 60 65]
 [70 75 80 85 90 95]]


(3, 6)

reverse a vector

In [57]:
z= np.arange(50)
print(z)

z=z[::-1]
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Create a 3x3 matrix of values 0 to 8

In [60]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Find indices of non zero values

In [62]:
n=z.nonzero()
n

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

Identity Matrix

In [64]:
z= np.eye(5)
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Random 3x3x3 matrix

In [75]:
z= np.random.random((3,3,3))
z

array([[[0.1540659 , 0.18599074, 0.50939127],
        [0.37162935, 0.67897786, 0.39887572],
        [0.52301666, 0.45814601, 0.48827968]],

       [[0.41265664, 0.76563926, 0.44808735],
        [0.73329779, 0.60740026, 0.71873367],
        [0.34366222, 0.60741028, 0.62910793]],

       [[0.45620468, 0.60546036, 0.8056359 ],
        [0.61603267, 0.97400764, 0.530572  ],
        [0.26706632, 0.68092559, 0.3920251 ]]])

Random Vector of size 30 and calculate the Mean

In [80]:
z= np.random.random(30)
print(z)
print(z.mean(),z.max(),z.min())

[0.17576604 0.10442419 0.04518138 0.15210052 0.5593277  0.01786796
 0.96560195 0.71449201 0.43058818 0.09595998 0.01781511 0.83563537
 0.31291958 0.46191443 0.09444223 0.98656484 0.89845006 0.5585605
 0.1357619  0.19340443 0.17703721 0.99341425 0.22094534 0.90332584
 0.35880578 0.07542101 0.62714553 0.67065201 0.12163905 0.79840432]
0.42345229044604366 0.9934142508269367 0.017815106794699


DataFrame to Numpy arrays

In [86]:
import pandas as pd

df = pd.DataFrame({'a1': [1, 2, 3],
                     'a2': [4,5,6]},
                     index=['X', 'Y', 'Z'])
print(df)


#DF to Numpy 
x= df.to_numpy()
print(x)

#particular Column
x= df['a1'].to_numpy()
print(x)


#Indexes of Df
x= df.index.to_numpy()
print(x)

   a1  a2
X   1   4
Y   2   5
Z   3   6
[[1 4]
 [2 5]
 [3 6]]
[1 2 3]
['X' 'Y' 'Z']


Nth Column of an NumPy array

In [97]:
z= np.array([[1,2,5],[3,4,5],[5,6,3],[7,8,4]])
print(z)

#all the rows
print(z[:,0])

print(z[2,:])

print(z[3,0])

[[1 2 5]
 [3 4 5]
 [5 6 3]
 [7 8 4]]
[1 3 5 7]
[5 6 3]
7


Dates of Yesterday, today, and tomorrow

In [105]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D') 
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print(yesterday,today,tomorrow)

2023-01-24 2023-01-25 2023-01-26


Dates of a Month

In [124]:
z= np.arange('2020-08','2020-09',dtype='datetime64[D]')
print(z)

['2020-08-01' '2020-08-02' '2020-08-03' '2020-08-04' '2020-08-05'
 '2020-08-06' '2020-08-07' '2020-08-08' '2020-08-09' '2020-08-10'
 '2020-08-11' '2020-08-12' '2020-08-13' '2020-08-14' '2020-08-15'
 '2020-08-16' '2020-08-17' '2020-08-18' '2020-08-19' '2020-08-20'
 '2020-08-21' '2020-08-22' '2020-08-23' '2020-08-24' '2020-08-25'
 '2020-08-26' '2020-08-27' '2020-08-28' '2020-08-29' '2020-08-30'
 '2020-08-31']


linspace

In [125]:
z = np.linspace(0,1,11, endpoint=False)
print(z)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


Generate 10 random numbers and sort them

In [128]:
z = np.random.random((10))
z.sort()
z

array([0.14416666, 0.35348705, 0.57581858, 0.69097535, 0.77892126,
       0.84498741, 0.86251197, 0.88439139, 0.94684958, 0.95220319])